In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("../data/raw/Global_Superstore.csv", sep=",", encoding="latin1")

In [4]:
# first 5 rows of the dataset
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [5]:
# last 5 rows of the dataset
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [6]:
# shape of the dataset
df.shape

(9994, 21)

In [7]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [8]:
df.dtypes

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [10]:
# descriptive statistics of the dataset
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [11]:
# check for missing values in the dataset
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [12]:
# check for duplicate rows in the dataset
df.duplicated().sum()

np.int64(0)

In [13]:
# convert column names to lowercase (snake_case) and replace spaces with underscores 
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("-", "_")
)

In [14]:
print(df.columns)

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub_category',
       'product_name', 'sales', 'quantity', 'discount', 'profit'],
      dtype='str')

In [15]:
# finding unique customer IDs in the dataset
df['customer_id'].nunique()

793

In [16]:
#finding unique product IDs in the dataset
df['product_id'].nunique()

1862

In [17]:
# mixed date formats in the order_date and ship_date columns, so we will convert them to datetime format using pd.to_datetime() function with errors='coerce' parameter to handle any invalid date formats.

df["order_date"] = pd.to_datetime(
    df["order_date"],
    format="mixed",
    errors="coerce"
)

df["ship_date"] = pd.to_datetime(
    df["ship_date"],
    format="mixed",
    errors="coerce"
)

In [18]:
# checks for missing values in the order_date column
df[df["order_date"].isna()]

Empty DataFrame
Columns: [row_id, order_id, order_date, ship_date, ship_mode, customer_id, customer_name, segment, country, city, state, postal_code, region, product_id, category, sub_category, product_name, sales, quantity, discount, profit]
Index: []

[0 rows x 21 columns]

In [19]:

# checks for missing values in the ship_date column
df[df["ship_date"].isna()]

Empty DataFrame
Columns: [row_id, order_id, order_date, ship_date, ship_mode, customer_id, customer_name, segment, country, city, state, postal_code, region, product_id, category, sub_category, product_name, sales, quantity, discount, profit]
Index: []

[0 rows x 21 columns]

In [20]:
df["order_date"].dtype
df["ship_date"].dtype

dtype('<M8[us]')

In [21]:
df["order_date"].head(10)

0   2016-11-08
1   2016-11-08
2   2016-06-12
3   2015-10-11
4   2015-10-11
5   2014-06-09
6   2014-06-09
7   2014-06-09
8   2014-06-09
9   2014-06-09
Name: order_date, dtype: datetime64[us]

In [22]:
# converting the data types of the columns to appropriate types

# string column to integer column
int_columns = [
    "row_id",
    "quantity",
    "postal_code"
]
df[int_columns] = df[int_columns].astype("int64")

# string column to float column
float_columns = [ 
    "sales",
    "discount",
    "profit"
]
df[float_columns] = df[float_columns].astype("float64")

# string column for date to datetime column
date_columns = [
    "order_date",
    "ship_date"
]
for col in date_columns:
    df[col] = pd.to_datetime(df[col], dayfirst=True)

In [23]:
category_columns = [
    "order_id",
    "ship_mode",
    "customer_id",
    "customer_name",
    "segment",
    "country",
    "city",
    "state",
    "region",
    "product_id",
    "category",
    "sub_category",
    "product_name"
]

df[category_columns] = df[category_columns].astype("category")

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   row_id         9994 non-null   int64
 1   order_id       9994 non-null   category
 2   order_date     9994 non-null   datetime64[us]
 3   ship_date      9994 non-null   datetime64[us]
 4   ship_mode      9994 non-null   category
 5   customer_id    9994 non-null   category
 6   customer_name  9994 non-null   category
 7   segment        9994 non-null   category
 8   country        9994 non-null   category
 9   city           9994 non-null   category
 10  state          9994 non-null   category
 11  postal_code    9994 non-null   int64
 12  region         9994 non-null   category
 13  product_id     9994 non-null   category
 14  category       9994 non-null   category
 15  sub_category   9994 non-null   category
 16  product_name   9994 non-null   category
 17  sales          9994 non-null   float64
 18  quantity       9994 non-null   int64
 19  discount       9994 non-null   float64
 20  profit         9994 non-null   float64
dtypes: category(13), datetime64[us](2), float64(3), int64(3)
memory usage: 895.6 KB

------------------------------------------------- DATA CLEANING DONE -----------------------------------------------------

In [25]:
# finding the sales range
df["sales"].min(), df["sales"].max()

(np.float64(0.444), np.float64(22638.48))

In [26]:
#finding the profit range
df["profit"].min(), df["profit"].max()

(np.float64(-6599.978), np.float64(8399.976))

----------------------------------------------- Feature Engineering ---------------------------------------------------------

In [27]:
# extra column - 1, delivery_days

# calculating the delivery days for each order 
df["delivery_days"] = (
    df["ship_date"] - df["order_date"]
).dt.days

In [28]:
df["delivery_days"].describe()

count    9994.000000
mean        3.958175
std         1.747567
min         0.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         7.000000
Name: delivery_days, dtype: float64

In [29]:
#extra column - 2, profit_margin

# calculating the profit margin for each order
df["profit_margin"] = np.where(
    df["sales"] != 0,
    (df["profit"] / df["sales"]) * 100,
    0
)

In [30]:
df["profit_margin"].describe()

count    9994.000000
mean       12.031393
std        46.675435
min      -275.000000
25%         7.500000
50%        27.000000
75%        36.250000
max        50.000000
Name: profit_margin, dtype: float64

In [31]:
# extra column - 3, order_year

# calculating the order year for each order
df["order_year"] = df["order_date"].dt.year

In [32]:
df["order_year"].describe()

count    9994.000000
mean     2015.722233
std         1.123555
min      2014.000000
25%      2015.000000
50%      2016.000000
75%      2017.000000
max      2017.000000
Name: order_year, dtype: float64

In [33]:
# extra column - 4, order_month

# calculating the order month for each order
df["order_month"] = df["order_date"].dt.month_name()

In [34]:
df["order_month"].describe()

count         9994
unique          12
top       November
freq          1471
Name: order_month, dtype: object

In [35]:
# extra column - 5, order_quarter

# calculating the order quarter for each order
df["order_quarter"] = df["order_date"].dt.quarter

In [36]:
df["order_quarter"].describe()

count    9994.000000
mean        2.882329
std         1.058086
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         4.000000
Name: order_quarter, dtype: float64

In [37]:
# extra column - 6, order_weekday

# calculating the order weekday for each order
df["order_weekday"] = df["order_date"].dt.day_name()

In [38]:
df["order_weekday"].describe()

count       9994
unique         7
top       Monday
freq        1871
Name: order_weekday, dtype: object

In [39]:
# checking for missing values in the newly created columns
new_columns = [
    "delivery_days",
    "profit_margin",
    "order_year",
    "order_month",
    "order_quarter",
    "order_weekday"
]

df[new_columns].isnull().sum()

delivery_days    0
profit_margin    0
order_year       0
order_month      0
order_quarter    0
order_weekday    0
dtype: int64

In [40]:
# finding the first and last order date in the dataset without the time component
df["order_date"].min().date(), df["order_date"].max().date()

(datetime.date(2014, 1, 3), datetime.date(2017, 12, 30))

In [41]:
# finding the first and last order date in the dataset with time component (not mentioned in the dataset but pandas added the default time component as 00:00:00)
df["order_date"].min(), df["order_date"].max()

(Timestamp('2014-01-03 00:00:00'), Timestamp('2017-12-30 00:00:00'))

In [42]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,sales,quantity,discount,profit,delivery_days,profit_margin,order_year,order_month,order_quarter,order_weekday
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,261.9600,2,0.00,41.9136,3,16.00,2016,November,4,Tuesday
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,731.9400,3,0.00,219.5820,3,30.00,2016,November,4,Tuesday
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,14.6200,2,0.00,6.8714,4,47.00,2016,June,2,Sunday
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,957.5775,5,0.45,-383.0310,7,-40.00,2015,October,4,Sunday
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,22.3680,2,0.20,2.5164,7,11.25,2015,October,4,Sunday

In [43]:
# Saving the cleaned data to work on for future

df.to_csv(
    "../data/cleaned/Global_Superstore_cleaned.csv",
    index=False
)